{
 "title": "MODEL FEEDBACK/RATING",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "RATINGS - GOOGLE FLAN-T5",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(feedback_stars_total{namespace=\"$namespace\", model_id=\"google/flan-t5-xl\"}) by (stars)"
    }
   ]
  },
  {
   "title": "RATINGS - MISTRAL MODEL",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(feedback_stars_total{namespace=\"$namespace\", model_id=\"mistralai/Mistral-7B-Instruct-v0.1\"}) by (stars)\n"
    }
   ]
  },
  {
   "title": "AVERAGE RATINGS - google/flan-t5-xl",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "repeat": "ModelID",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum((feedback_stars_total{namespace=\"$namespace\", stars=\"1\", model_id=\"google/flan-t5-xl\"} or on() vector(0))* 1) + sum((feedback_stars_total{namespace=\"$namespace\", stars=\"2\", model_id=\"google/flan-t5-xl\"} or on() vector(0)) * 2) +\nsum((feedback_stars_total{namespace=\"$namespace\", stars=\"3\", model_id=\"google/flan-t5-xl\"} or on() vector(0)) * 3) + sum((feedback_stars_total{namespace=\"$namespace\", stars=\"4\", model_id=\"google/flan-t5-xl\"} or on() vector(0)) * 4) +\nsum((feedback_stars_total{namespace=\"$namespace\", stars=\"5\", model_id=\"google/flan-t5-xl\"} or on() vector(0)) * 5)) \n/\n(sum(feedback_stars_total{namespace=\"$namespace\", stars=\"1\", model_id=\"google/flan-t5-xl\"} or on() vector(0)) + sum(feedback_stars_total{namespace=\"$namespace\", stars=\"2\", model_id=\"google/flan-t5-xl\"} or on() vector(0)) + sum(feedback_stars_total{namespace=\"$namespace\", stars=\"3\", model_id=\"google/flan-t5-xl\"} or on() vector(0)) + sum(feedback_stars_total{namespace=\"$namespace\", stars=\"4\", model_id=\"google/flan-t5-xl\"} or on() vector(0)) + sum(feedback_stars_total{namespace=\"$namespace\", stars=\"5\", model_id=\"google/flan-t5-xl\"} or on() vector(0)))\n"
    }
   ]
  },
  {
   "title": "AVERAGE RATING  - MISTRAL MODEL",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum((feedback_stars_total{namespace=\"$namespace\", stars=\"1\", model_id=\"mistralai/Mistral-7B-Instruct-v0.1\"} or on() vector(0))* 1) + sum((feedback_stars_total{namespace=\"$namespace\", stars=\"2\", model_id=\"mistralai/Mistral-7B-Instruct-v0.1\"} or on() vector(0)) * 2) +\nsum((feedback_stars_total{namespace=\"$namespace\", stars=\"3\", model_id=\"mistralai/Mistral-7B-Instruct-v0.1\"} or on() vector(0)) * 3) + sum((feedback_stars_total{namespace=\"$namespace\", stars=\"4\", model_id=\"mistralai/Mistral-7B-Instruct-v0.1\"} or on() vector(0)) * 4) +\nsum((feedback_stars_total{namespace=\"$namespace\", stars=\"5\", model_id=\"mistralai/Mistral-7B-Instruct-v0.1\"} or on() vector(0)) * 5)) \n/\n(sum(feedback_stars_total{namespace=\"$namespace\", stars=\"1\", model_id=\"mistralai/Mistral-7B-Instruct-v0.1\"} or on() vector(0)) + sum(feedback_stars_total{namespace=\"$namespace\", stars=\"2\", model_id=\"mistralai/Mistral-7B-Instruct-v0.1\"} or on() vector(0)) + sum(feedback_stars_total{namespace=\"$namespace\", stars=\"3\", model_id=\"mistralai/Mistral-7B-Instruct-v0.1\"} or on() vector(0)) + sum(feedback_stars_total{namespace=\"$namespace\", stars=\"4\", model_id=\"mistralai/Mistral-7B-Instruct-v0.1\"} or on() vector(0)) + sum(feedback_stars_total{namespace=\"$namespace\", stars=\"5\", model_id=\"mistralai/Mistral-7B-Instruct-v0.1\"} or on() vector(0)))"
    }
   ]
  },
  {
   "title": "MODEL USAGE",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (model_id) (model_usage_total{model_id=\"google/flan-t5-xl\", namespace=\"$namespace\"})",
     "legendFormat": "{{model_id}}"
    },
    {
     "expr": "sum by (model_id) (model_usage_total{model_id=\"mistralai/Mistral-7B-Instruct-v0.1\", namespace=\"$namespace\"})",
     "legendFormat": "{{model_id}}"
    }
   ]
  },
  {
   "title": "REQUEST TIME ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (model_id) (request_duration_seconds{model_id=\"google/flan-t5-xl\"})",
     "legendFormat": "{{model_id}}"
    },
    {
     "expr": "sum by (model_id) (request_duration_seconds{model_id=\"mistralai/Mistral-7B-Instruct-v0.1\"})",
     "legendFormat": "{{model_id}}"
    }
   ]
  }
 ]
}